### PR TITLE
Hook up analysis

### PR DESCRIPTION
**Pull request by mcnuttandrew**

### CODE REVIEW

**Comment by mcorrell** [comment]
Do the nulls/invalid values actually show up in the histogram? Or does vegalite filter out to just the valid values before rendering

**Comment by mcorrell** [comment]
Also thanks for refactoring the card object generation, it was driving me nuts. (Probably the right thing to do would be for me to just have different "strength" functions and then just one minor arcana generation function, rather than the four largely redundant functions here, but it seemed easier to have individual functions to tweak for testing purposes).

**Comment by mcnuttandrew** [comment]
> Also thanks for refactoring the card object generation, it was driving me nuts.

it was absolutely a pleasure to do, i find that it's way easier to work on a piece of code after you refactor it a little. That way you sort understand the logic of the piece, so this was perfect.

I kinda like having four separate generation functions, it makes it feel pretty easy to understand

**Comment by mcnuttandrew** [comment]
I'm gonna merge this branch in and continue to iterate on the charts because they are sort of a seperate issue than hooking together the analyses

**Pull request merged**
