### PR TITLE
Loading Data / Spreads

### PR DESCRIPTION
**Pull request by mcnuttandrew**
First pass at the UI for loading data / spreads

Screen Shot 2019-12-20 at 11 13 46 AM

### CODE REVIEW

**Comment by mcorrell** [comment]
LGTM! Did you want to keep working on hooking this up or did you want me to merge?

**Comment by mcnuttandrew** [comment]
I'll wrap up the little feature i'm working on right now and then merge it, specifically i'm handling the responsive layout (great minds) and tooltips

**Comment by mcorrell** [comment]
Okay, ping me when you want to merge. My plan is to mess with analysis.js later today so nothing should be blocking anything as far as I'm concerned.

**Comment by mcnuttandrew** [comment]
Alright so i wasn't able to get the responsive parts working in the end, but i do a lot of small ux things. If you are wanting to analysis stuff the architecture i have now just asks you to fill out the function computeCards which will generate the deck (including all relevant analyses)

**Pull request merged**
