### PR TITLE
Add upload and other datasources

### PR DESCRIPTION
**Pull request by mcnuttandrew**
Adds datasource from https://www.ers.usda.gov/data-products/dairy-data/ which helps address #17

### CODE REVIEW

**Comment by mcorrell** [comment]
Is the only thing I need to do to add new datasets to update the <options> tag or is there more sorcery I need to do.

Also for the current random minor arcana, might want to use data lib to filter to fields of just type number/integer or VegaLite might barg.

**Comment by mcnuttandrew** [comment]
> Is the only thing I need to do to add new datasets to update the tag or is there more sorcery I need to do.

All you now need to do to add additional datasets is to put them into the data folder and add a corresponding <option> tag in the html.

> Also for the current random minor arcana, might want to use data lib to filter to fields of just type number/integer or VegaLite might barg.

I do exactly that in the computeCards / emptyMinorArcana functions in main right now! Nice that we're on the same page here

**Comment by amcrisan** [comment]
Merged it because I was also working on those functions and those are changes that change how I doing the sampling.

**Comment by amcrisan** [comment]
@mcnuttandrew Maybe it's just for me, but the deck seems to have disappeared. Stashed all my changes and just went with yours

**Comment by amcrisan** [comment]
Never mind .. it really was just me.

**Pull request merged**
