### PR TITLE
Null histogram

### PR DESCRIPTION
**Pull request by mcnuttandrew**
A null histogram written in vega, also includes some improvements to the card tops

### CODE REVIEW

**Comment by mcorrell** [comment]
Would the signal you're using pull out the "" and '' and undefineds and so on? Those get flagged by the analysis function as equivalent to nulls?

**Comment by mcnuttandrew** [comment]
Good catch! This was copped from a vega example, so needs some further messaging to handle more than basic cases.

**Comment by mcnuttandrew** [comment]
the datalib profiler is still a little bit aggressive with it's inferences (it thinks a lot of things are strings when they are in fact just corrupted data). I'm not really sure how we can get around that without a ton of work??

**Comment by mcorrell** [comment]
I _think_ that the type inference is based on just the first row of the data, so that suggests some hacky fixes. I know world indicators has some weirdness too (some value are "xM" to indicate millions, others are "$x" or what have you...

**Pull request merged**
