### PR TITLE
Mcorrell analysis

### PR DESCRIPTION
**Pull request by mcorrell**
Okay. Initial stab at doing analyses for the minor arcana.
Pentacles: top quantitative fields with outliers (ranked by z score)
Wands: top quantitative x categorical x aggregation functions (ranked by variance in values compared to variance of the quantitative field in general)
Cups: top quantitative x quantitative fields (ranked by pearson's r)
Swords: top bad fields (ranked by number of nulls/NaNs).

### CODE REVIEW

**Comment by mcorrell** [comment]
@mcnuttandrew I sort of want to just play around with the functions in the console, but I'm assuming the actual current dataset is encapsulated in main()?

**Comment by mcorrell** [comment]
Also @amcrisan @mcnuttandrew let me know if you have thoughts; the idea here is to just do dirt-simple things to p-hack some interesting graphs.

**Comment by mcnuttandrew** [comment]
> @mcnuttandrew I sort of want to just play around with the functions in the console, but I'm assuming the actual current dataset is encapsulated in main()?

Yes that correct. If you want to make it so that everyone everywhere can see the data change stateUpdate like this:


```js
// update the state of the system based on changed inputs
  function stateUpdate() {
    // if layout and data aren't specified don't do anything
    if (!(state.layout && state.data)) {
      return;
    }
    // compute the cards
    state.cards = computeCards(state.data);
    // this is the new line
    window.data = state.data;

    // remove the placeholder content
    const placeHolder = document.querySelector('#load-msg');
    if (placeHolder) {
      placeHolder.remove();
    }

    // size the mainContainer correctly
    const {height, width} = container.getBoundingClientRect();
    mainContainer.style('height', `${height}px`);
    mainContainer.style('width', `${width}px`);

    // draw the layout
    buildLayout(mainContainer, state.layout, state.cards, state.data);
  }
```

**Comment by mcorrell** [comment]
Eh, that seems a little silly to break encapsulation. I'll just write some tests like an adult...

Also since stateUpdate gets called after window resizes as well as these sorts of changes, doesn't that mean that cards will be removed every time you mess with the window?

**Comment by mcnuttandrew** [comment]
> Eh, that seems a little silly to break encapsulation. I'll just write some tests like an adult...

Don't worry about that, just do whatever works for you for now and we'll fix it later if we need to.

> Also since stateUpdate gets called after window resizes as well as these sorts of changes, doesn't that mean that cards will be removed every time you mess with the window?

That's true, and is something I need to fix

**Comment by mcnuttandrew** [comment]
Merging so that I can work on adding the adaptations discussed in the hangout

**Pull request merged**
